// -- Classic community presets --------------------------------------------------
// Seed definitions for well-known community palettes, keeping their canonical
// names. Each preset specifies only its seed tokens; deriveTheme fills the
// alpha + shade tokens.

import type { Theme } from "@/domain/theme/model";
import { DARK_ONSET, LIGHT_ONSET } from "@/domain/theme/onset-constants";
import { DARK_SNAP, LIGHT_SNAP } from "@/domain/theme/snap-constants";

const CLASSIC_PRESETS: Theme[] = [
  {
    id: "dracula",
    name: "Dracula",
    kind: "preset",
    group: "Classics",
    scheme: "dark",
    desc: "The vampire palette.",
    tokens: {
      bg: "#282a36",
      "bg-dark": "#21222c",
      "bg-elevated": "#343746",
      text: "#f8f8f2",
      "text-tertiary": "#bcc0d4",
      "text-faint": "#6272a4",
      accent: "#bd93f9",
      "accent-warm": "#ffb86c",
      link: "#8be9fd",
      error: "#ff5555",
      "error-text": "#ffe5e5",
      warning: "#f1fa8c",
      explicit: "#ff79c6",
      wave: "#44475a",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
  {
    id: "nord",
    name: "Nord",
    kind: "preset",
    group: "Classics",
    scheme: "dark",
    desc: "Arctic, north-bluish.",
    tokens: {
      bg: "#2e3440",
      "bg-dark": "#272c36",
      "bg-elevated": "#3b4252",
      text: "#eceff4",
      "text-tertiary": "#d8dee9",
      "text-faint": "#7b88a1",
      accent: "#88c0d0",
      "accent-warm": "#d08770",
      link: "#81a1c1",
      error: "#bf616a",
      "error-text": "#ffe5e5",
      warning: "#ebcb8b",
      explicit: "#b48ead",
      wave: "#4c566a",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    kind: "preset",
    group: "Classics",
    scheme: "dark",
    desc: "Ethan Schoonover's classic.",
    tokens: {
      bg: "#002b36",
      "bg-dark": "#00212b",
      "bg-elevated": "#073642",
      text: "#fdf6e3",
      "text-tertiary": "#93a1a1",
      "text-faint": "#586e75",
      accent: "#268bd2",
      "accent-warm": "#cb4b16",
      link: "#2aa198",
      error: "#dc322f",
      "error-text": "#fdf6e3",
      warning: "#b58900",
      explicit: "#d33682",
      wave: "#33555f",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    kind: "preset",
    group: "Classics",
    scheme: "light",
    desc: "Same hues, paper base.",
    tokens: {
      bg: "#fdf6e3",
      "bg-dark": "#eee8d5",
      "bg-elevated": "#ffffff",
      text: "#073642",
      "text-tertiary": "#586e75",
      "text-faint": "#93a1a1",
      accent: "#268bd2",
      "accent-warm": "#cb4b16",
      link: "#2aa198",
      error: "#dc322f",
      "error-text": "#7a1f1c",
      warning: "#b58900",
      explicit: "#d33682",
      wave: "#cfcbb8",
      snap: LIGHT_SNAP,
      onset: LIGHT_ONSET,
    },
  },
  {
    id: "gruvbox",
    name: "Gruvbox",
    kind: "preset",
    group: "Classics",
    scheme: "dark",
    desc: "Retro warm earth tones.",
    tokens: {
      bg: "#282828",
      "bg-dark": "#1d2021",
      "bg-elevated": "#3c3836",
      text: "#ebdbb2",
      "text-tertiary": "#bdae93",
      "text-faint": "#928374",
      accent: "#fabd2f",
      "accent-warm": "#fe8019",
      link: "#83a598",
      error: "#fb4934",
      "error-text": "#fff0ea",
      warning: "#d79921",
      explicit: "#d3869b",
      wave: "#504945",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    kind: "preset",
    group: "Classics",
    scheme: "dark",
    desc: "Neon over deep indigo.",
    tokens: {
      bg: "#1a1b26",
      "bg-dark": "#16161e",
      "bg-elevated": "#24283b",
      text: "#c0caf5",
      "text-tertiary": "#9aa5ce",
      "text-faint": "#565f89",
      accent: "#7aa2f7",
      "accent-warm": "#ff9e64",
      link: "#2ac3de",
      error: "#f7768e",
      "error-text": "#ffe5ea",
      warning: "#e0af68",
      explicit: "#bb9af7",
      wave: "#3b4261",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
  {
    id: "catppuccin",
    name: "Catppuccin Mocha",
    kind: "preset",
    group: "Classics",
    scheme: "dark",
    desc: "Soft pastel, mocha base.",
    tokens: {
      bg: "#1e1e2e",
      "bg-dark": "#181825",
      "bg-elevated": "#313244",
      text: "#cdd6f4",
      "text-tertiary": "#a6adc8",
      "text-faint": "#7f849c",
      accent: "#cba6f7",
      "accent-warm": "#fab387",
      link: "#89dceb",
      error: "#f38ba8",
      "error-text": "#ffe5ec",
      warning: "#f9e2af",
      explicit: "#f5c2e7",
      wave: "#45475a",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
  {
    id: "rose-pine",
    name: "Rosé Pine",
    kind: "preset",
    group: "Classics",
    scheme: "dark",
    desc: "Muted, all natural pine.",
    tokens: {
      bg: "#191724",
      "bg-dark": "#13111e",
      "bg-elevated": "#26233a",
      text: "#e0def4",
      "text-tertiary": "#908caa",
      "text-faint": "#6e6a86",
      accent: "#c4a7e7",
      "accent-warm": "#ebbcba",
      link: "#9ccfd8",
      error: "#eb6f92",
      "error-text": "#ffe5ec",
      warning: "#f6c177",
      explicit: "#ebbcba",
      wave: "#403d52",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
  {
    id: "one-dark",
    name: "One Dark",
    kind: "preset",
    group: "Classics",
    scheme: "dark",
    desc: "Atom's signature palette.",
    tokens: {
      bg: "#282c34",
      "bg-dark": "#21252b",
      "bg-elevated": "#2c313a",
      text: "#abb2bf",
      "text-tertiary": "#828997",
      "text-faint": "#5c6370",
      accent: "#61afef",
      "accent-warm": "#e5c07b",
      link: "#56b6c2",
      error: "#e06c75",
      "error-text": "#ffe5e5",
      warning: "#d19a66",
      explicit: "#c678dd",
      wave: "#4b5263",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
];

export { CLASSIC_PRESETS };
