// -- Composer house presets ----------------------------------------------------
// Seed definitions for the Composer-made themes. Each preset specifies only its
// seed tokens; deriveTheme fills the alpha + shade tokens. The Default preset
// pins the three accent shades explicitly so it reproduces the exact current
// look (the rgb values in src/index.css do not equal the shade formula).

import type { Theme } from "@/domain/theme/model";
import { DARK_ONSET, LIGHT_ONSET } from "@/domain/theme/onset-constants";
import { DARK_SNAP, LIGHT_SNAP } from "@/domain/theme/snap-constants";

const COMPOSER_PRESETS: Theme[] = [
  {
    id: "default",
    name: "Default",
    kind: "preset",
    group: "Composer",
    scheme: "dark",
    desc: "Indigo on charcoal. The house look.",
    tokens: {
      bg: "#28292c",
      "bg-dark": "#1a1a1c",
      "bg-elevated": "#3e3e41",
      text: "#ffffff",
      "text-tertiary": "#aaaaaa",
      "text-faint": "#696b77",
      accent: "#818cf8",
      "accent-dark": "#6470dc",
      "accent-darker": "#505ac8",
      "accent-text": "#a5b4fc",
      "accent-warm": "#d4a5a5",
      link: "#5865f2",
      error: "#b45555",
      "error-text": "#ffe5e5",
      warning: "#f5a623",
      explicit: "#ff7a85",
      wave: "#737476",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
  {
    id: "light",
    name: "Light",
    kind: "preset",
    group: "Composer",
    scheme: "light",
    desc: "Seek help",
    tokens: {
      bg: "#f7f7f8",
      "bg-dark": "#ececef",
      "bg-elevated": "#ffffff",
      text: "#1b1c1f",
      "text-tertiary": "#5b5d63",
      "text-faint": "#9a9ca5",
      accent: "#818cf8",
      "accent-dark": "#a5b4fc",
      "accent-darker": "#818cf8",
      "accent-text": "#5b63e0",
      "accent-warm": "#b06a6a",
      link: "#4750d8",
      error: "#c2453f",
      "error-text": "#7a1f1c",
      warning: "#b9791a",
      explicit: "#d65560",
      wave: "#c4c5ca",
      snap: LIGHT_SNAP,
      onset: LIGHT_ONSET,
    },
  },
  {
    id: "high-contrast",
    name: "High contrast",
    kind: "preset",
    group: "Composer",
    scheme: "dark",
    desc: "Brighter text, harder borders, AA+.",
    tokens: {
      bg: "#000000",
      "bg-dark": "#000000",
      "bg-elevated": "#161616",
      text: "#ffffff",
      "text-tertiary": "#e6e6e6",
      "text-faint": "#b8b8b8",
      accent: "#818cf8",
      "accent-dark": "#6470dc",
      "accent-darker": "#505ac8",
      "accent-text": "#a5b4fc",
      "accent-warm": "#ffc0c0",
      link: "#9aa6ff",
      error: "#ff8080",
      "error-text": "#ffffff",
      warning: "#ffc24d",
      explicit: "#ff9aa3",
      wave: "#9a9a9a",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
  {
    id: "harbor",
    name: "Harbor",
    kind: "preset",
    group: "Composer",
    scheme: "dark",
    desc: "Cool navy, steel-blue accent.",
    tokens: {
      bg: "#0f1b2d",
      "bg-dark": "#0a131f",
      "bg-elevated": "#16273d",
      text: "#eaf1fb",
      "text-tertiary": "#9fb3cc",
      "text-faint": "#5d7790",
      accent: "#5aa9e6",
      "accent-warm": "#e0a86a",
      link: "#6fb6ef",
      error: "#d96a6a",
      "error-text": "#ffe5e5",
      warning: "#e6a84d",
      explicit: "#ff8a93",
      wave: "#3f5a78",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
  {
    id: "moss",
    name: "Moss",
    kind: "preset",
    group: "Composer",
    scheme: "dark",
    desc: "Forest greens, warm sap accent.",
    tokens: {
      bg: "#1a2620",
      "bg-dark": "#121c17",
      "bg-elevated": "#243530",
      text: "#e9f1ec",
      "text-tertiary": "#9bb3a6",
      "text-faint": "#5f7a6e",
      accent: "#6fc28a",
      "accent-warm": "#d4b483",
      link: "#7fcf9a",
      error: "#cf6f6f",
      "error-text": "#ffe9e9",
      warning: "#d9a84d",
      explicit: "#ff8e8e",
      wave: "#3e5a4c",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
  {
    id: "rosewater",
    name: "Rosewater",
    kind: "preset",
    group: "Composer",
    scheme: "dark",
    desc: "Warm plum dark, dusty rose accent.",
    tokens: {
      bg: "#2a1f26",
      "bg-dark": "#1d151b",
      "bg-elevated": "#392a33",
      text: "#f6ecf1",
      "text-tertiary": "#c2a8b6",
      "text-faint": "#856b78",
      accent: "#e08aa6",
      "accent-warm": "#e0b27a",
      link: "#e69bb4",
      error: "#d96a6a",
      "error-text": "#ffe5e5",
      warning: "#e0a84d",
      explicit: "#ff8a93",
      wave: "#5e4452",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
  {
    id: "graphite",
    name: "Graphite",
    kind: "preset",
    group: "Composer",
    scheme: "dark",
    desc: "Pure monochrome. No hue.",
    tokens: {
      bg: "#1e1e1e",
      "bg-dark": "#141414",
      "bg-elevated": "#2b2b2b",
      text: "#f0f0f0",
      "text-tertiary": "#a8a8a8",
      "text-faint": "#6a6a6a",
      accent: "#cfcfcf",
      "accent-warm": "#9a9a9a",
      link: "#bcbcbc",
      error: "#c98a8a",
      "error-text": "#ffeaea",
      warning: "#cbb27a",
      explicit: "#d99a9a",
      wave: "#555555",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
  {
    id: "ember",
    name: "Ember",
    kind: "preset",
    group: "Composer",
    scheme: "dark",
    desc: "Warm coals, amber glow.",
    tokens: {
      bg: "#221a14",
      "bg-dark": "#1a130e",
      "bg-elevated": "#30241a",
      text: "#f5ece2",
      "text-tertiary": "#c2ad97",
      "text-faint": "#7a6a59",
      accent: "#e8a14d",
      "accent-warm": "#e0b27a",
      link: "#f0b860",
      error: "#d96a6a",
      "error-text": "#ffe5e5",
      warning: "#e6c14d",
      explicit: "#ff8a93",
      wave: "#5a4a38",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
  {
    id: "tide",
    name: "Tide",
    kind: "preset",
    group: "Composer",
    scheme: "dark",
    desc: "Deep water, teal accent.",
    tokens: {
      bg: "#0f1f22",
      "bg-dark": "#0a171a",
      "bg-elevated": "#163034",
      text: "#e6f1f0",
      "text-tertiary": "#9fc0bd",
      "text-faint": "#5d7d7a",
      accent: "#45c4c0",
      "accent-warm": "#e0a86a",
      link: "#5fd0cc",
      error: "#d96a6a",
      "error-text": "#ffe5e5",
      warning: "#e6a84d",
      explicit: "#ff8a93",
      wave: "#2f5450",
      snap: DARK_SNAP,
      onset: DARK_ONSET,
    },
  },
];

export { COMPOSER_PRESETS };
